### ISSUE TITLE
Seed database with legal values.

### ISSUE THREAD

**Issue by jerinphilip** [darkcoderrises/Movie-Recommender#1]
https://github.com/darkcoderrises/Movie-Recommender/blob/master/backend/movie_recommender/booking_system/management/commands/seed.py

Enhance this to encompass the full db schema, with seeded content.

**Comment by jerinphilip** [comment]
- [x] Genre
- [x] Language
- [ ] Mode - 3D, 2D, IMAX-3D
- [ ] Screen-Size (?)
- [ ] Users
- [x] Cast
- [ ] Movie
- [x] Theater
- [x] Seats - Fix random rows (A-Z) and columns (1-n), use to seed.
- [x] Shows
- [ ] Reservations
- [ ] Email Preferences

**Comment by jerinphilip** [comment]
So, we're in a tricky situation here. Recommendations require a few additional things, and a new dataset of sorts which is complete than the tiny one we had as `movies_metadata.csv`.

I'm prototyping a new mlens seeder, based on the movielens dataset. The script can currently be used to seed `Movie` and `CrewProfile`. The `Cast` requires more code, will take time. But given `Movie` is ready, you can seed `Show`, `Theatre` independent of the others.

What I'm suggesting is, the old seed script, remove the movie seeding parts, and use mlens instead and clean up the `Show` and `Theater` part in that script. Additionally, build views for `Show` and `Theater`.

**Comment by jerinphilip** [comment]
- [x] Remove/Comment out Movies, Cast logic from `seed.py`
- [x] Use `mlens.py` to seed the above two models, and associated relations.
- [x] Enhance Show, Screen, Theatre seeding logic. @shiva429 is on theatre CSVs and all that.
- [x] Build views for Show, Screen, Theatre etc. @AGangrade

**Comment by jerinphilip** [comment]
@AGangrade: Can we have a status update on the above checklist?

**Comment by AGangrade** [comment]
Only view for shows is remaining.

**Comment by AGangrade** [comment]
Seeding is done... Working on views
